export const DEFAULT_PERMISSION_OPTIONS = [
    { p_option_id: "task_create", name: "Create Task" },
    { p_option_id: "task_cancel", name: "Cancel Task" },
    { p_option_id: "task_complete", name: "Complete Task" },
    { p_option_id: "task_fees_view", name: "Fees View" },
    { p_option_id: "task_get_in", name: "Task Get In" },
    { p_option_id: "client_create", name: "Create Client" },
    { p_option_id: "client_edit", name: "Edit Client" },
    { p_option_id: "client_delete", name: "Delete Client" },
    { p_option_id: "finance_balance_view", name: "Balance View" },
    { p_option_id: "finance_entry", name: "Finance Entry" },
    { p_option_id: "finance_entry_edit", name: "Edit Entry" },
    { p_option_id: "finance_entry_delete", name: "Delete Entry" },
    { p_option_id: "finance_report", name: "Finance Report" },
    { p_option_id: "finance_billing_approve_reject", name: "Billing Approve" },
    { p_option_id: "broadcast_config_edit", name: "Broadcast Config" },
    { p_option_id: "broadcast_send", name: "Send Broadcast" },
    { p_option_id: "broadcast_livechat", name: "Live Chat" },
    { p_option_id: "setting_view_edit", name: "Settings" },
    { p_option_id: "subscription_manage", name: "Subscription" },
    { p_option_id: "staff_attendance_view_manage", name: "Staff & Attendance" },
    { p_option_id: "office_assistance_access", name: "Office Assistance" },
    { p_option_id: "recurring_task_create", name: "Compliance Create" },
    { p_option_id: "recurring_task_delete", name: "Compliance Delete" },
    { p_option_id: "recurring_task_complete", name: "Compliance Complete" },
    { p_option_id: "recurring_task_fees_view", name: "Compliance Fees" },
    { p_option_id: "sales_overview_view", name: "Sales Overview View" },
    { p_option_id: "quick_stats_view", name: "Quick Stats View" },
    { p_option_id: "task_summary_view", name: "Task Summary View" },
    { p_option_id: "service_wise_sales_view", name: "Service Wise Sales View" },
    { p_option_id: "staff_wise_sales_view", name: "Staff Wise Sales View" },
    { p_option_id: "top_clients_view", name: "Top Clients View" },
    { p_option_id: "dashboard_statistics_view", name: "Dashboard Statistics View" },
];

const ALL_PERMISSION_IDS = DEFAULT_PERMISSION_OPTIONS.map((opt) => opt.p_option_id);

const MANAGER_PERMISSIONS = [
    "task_create",
    "task_cancel",
    "task_complete",
    "task_fees_view",
    "task_get_in",
    "client_create",
    "client_edit",
    "finance_balance_view",
    "finance_report",
    "finance_billing_approve_reject",
    "broadcast_send",
    "broadcast_livechat",
    "staff_attendance_view_manage",
    "office_assistance_access",
    "recurring_task_create",
    "recurring_task_delete",
    "recurring_task_complete",
    "recurring_task_fees_view",
    "sales_overview_view",
    "quick_stats_view",
    "task_summary_view",
    "service_wise_sales_view",
    "staff_wise_sales_view",
    "top_clients_view",
    "dashboard_statistics_view",
];

const STAFF_PERMISSIONS = [
    "task_create",
    "task_complete",
    "task_fees_view",
    "task_get_in",
    "office_assistance_access",
    "quick_stats_view",
    "task_summary_view",
];

export const DEFAULT_GLOBAL_ROLES = [
    {
        permission_role_id: "PR_GLOBAL_DEFAULT_ADMIN",
        name: "Default Admin",
        remark: "Global default role with full operational access (excluding subscription management)",
        permissions: ALL_PERMISSION_IDS.filter((id) => id !== "subscription_manage"),
    },
    {
        permission_role_id: "PR_GLOBAL_DEFAULT_MANAGER",
        name: "Default Manager",
        remark: "Global default role for team leads and supervisors",
        permissions: MANAGER_PERMISSIONS,
    },
    {
        permission_role_id: "PR_GLOBAL_DEFAULT_STAFF",
        name: "Default Staff",
        remark: "Global default role for regular staff members",
        permissions: STAFF_PERMISSIONS,
    },
];
