import express from "express";
const router = express.Router();
import authRoutes from "./auth.js";
import subscriptionRoutes from "./subscription.js";
import clientRoutes from "./client.js";
import caRoutes from "./ca.js";
import adminRoutes from "./admin.js";
import agentRoutes from "./agent.js";
import taskRoutes from "./task.js";
import staffRoutes from "./staff.js";
import permissionRoutes from "./permission.js";
import webhookRoutes from "./webhook.js";
import emailRoutes from "./email.js";
import smsRoutes from "./sms.js";
import groupRoutes from "./group.js";
import firmRoutes from "./firm.js";
import serviceRoutes from "./service.js";
import transactionsRoutes from "./transactions.js";
import assistanceRoutes from "./assistance.js";
import utilsRoutes from "./utils.js";
import attendanceRoutes from "./attandance.js";
import saleRoutes from "./sale.js";
import purchaseRoutes from "./purchase.js";
import expenseRoutes from "./expense.js";
import billingRoutes from "./billing.js";
import reportRoutes from "../routes/report.js";
import invoiceRoutes from "./invoice.js";
import settingsRoutes from "./settings.js";
import loanRoutes from "./loan.js";
import quotationRoutes from "./quotation.js";
import staffexpenseRoutes from "./staff_expenses.js";
import contraRoutes from "./contra.js";
import journalRoutes from "./journal.js";
import capitalRoutes from "./capital.js";
import branchRoutes from "./branch.js";
import bulkmailRoutes from "./email_Import.js";
import exportRoutes from "./export.js";
import paymentreminderRoutes from "./payment_reminder.js";
import autopayRoutes from "./autopay.js";
import walletRoutes from "./wallet.js";
import complianceRoutes from "./compliance.js";
import whatsappRoutes from "./whatsapp.js";
import backupRoutes from "./backup.js";
import accountRoutes from "./account.js";


router.use("/auth", authRoutes);
router.use("/subscription", subscriptionRoutes);
router.use("/client", clientRoutes);
router.use("/ca", caRoutes);
router.use("/admin", adminRoutes);
router.use("/agent", agentRoutes);
router.use("/task", taskRoutes);
router.use("/settings/staff", staffRoutes);
// router.use("/settings/permission", permissionRoutes);
router.use("/settings/permissions", permissionRoutes);
router.use("/webhook", webhookRoutes);
router.use("/broadcast/email", emailRoutes);
router.use("/broadcast/sms", smsRoutes);
router.use("/broadcast/whatsapp", whatsappRoutes);
router.use("/group", groupRoutes);
router.use("/service", serviceRoutes);
router.use("/firm", firmRoutes);
router.use("/sale", saleRoutes);
router.use("/purchase", purchaseRoutes);
router.use("/transaction", transactionsRoutes);
router.use("/assistance", assistanceRoutes);
router.use("/utils", utilsRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/expense", expenseRoutes);
router.use("/billing", billingRoutes);
router.use("/report", reportRoutes);
router.use("/invoice", invoiceRoutes);
router.use("/settings", settingsRoutes);
router.use("/loan", loanRoutes);
router.use("/quotation", quotationRoutes);
router.use("/staff-expenses", staffexpenseRoutes);
router.use("/contra", contraRoutes);
router.use("/journal", journalRoutes);
router.use("/capital", capitalRoutes);
router.use("/branch", branchRoutes);
router.use("/bulkmail", bulkmailRoutes);
router.use("/export", exportRoutes);
router.use("/payment-reminder", paymentreminderRoutes);
router.use("/autopay", autopayRoutes);
router.use("/wallet", walletRoutes);
router.use("/compliance", complianceRoutes);
router.use("/recurring-task", complianceRoutes);
router.use("/backup", backupRoutes);
router.use("/account", accountRoutes);

export default router;
