-- Drop tax/GST amount columns (keep branch_list GST flags)
-- Generated by drop-tax-rate-columns.js

-- ALTER TABLE `tasks` DROP COLUMN `tax_rate`;
-- ALTER TABLE `tasks` DROP COLUMN `tax_value`;

-- ALTER TABLE `invoice` DROP COLUMN `tax_rate`;
-- ALTER TABLE `invoice` DROP COLUMN `tax_value`;

-- ALTER TABLE `sale_items` DROP COLUMN `tax_perc`;
-- ALTER TABLE `sale_items` DROP COLUMN `tax_value`;

-- ALTER TABLE `quotation_items` DROP COLUMN `tax_rate`;
-- ALTER TABLE `quotation_items` DROP COLUMN `tax_value`;

-- ALTER TABLE `compliance_firms` DROP COLUMN `tax_rate`;
-- ALTER TABLE `compliance_firms` DROP COLUMN `tax_value`;

-- ALTER TABLE `service_requests` DROP COLUMN `tax_rate`;
-- ALTER TABLE `service_requests` DROP COLUMN `tax_value`;

-- ALTER TABLE `branch_services` DROP COLUMN `gst_rate`;
-- ALTER TABLE `branch_services` DROP COLUMN `gst_value`;
