-- Merge salaries + staff_salary_assignments into a single staff_salaries table.

CREATE TABLE IF NOT EXISTS staff_salaries (
  id INT(11) NOT NULL AUTO_INCREMENT,
  salary_id VARCHAR(50) NOT NULL,
  map_id VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL,
  branch_id VARCHAR(50) NOT NULL,
  salary_type ENUM('fixed','flexible') NOT NULL DEFAULT 'fixed',
  amount DECIMAL(12,2) NOT NULL,
  monthly_working_hours DECIMAL(8,2) DEFAULT NULL COMMENT 'Required for flexible: hours to fulfill for full monthly salary',
  effective_from DATE NOT NULL,
  effective_to DATE DEFAULT NULL,
  is_active ENUM('0','1') DEFAULT '0',
  working_hours_start TIME DEFAULT '10:00:00',
  working_hours_end TIME DEFAULT '18:00:00',
  expected_hours DECIMAL(5,2) DEFAULT 8.00,
  grace_period_minutes INT(11) DEFAULT 10,
  overtime_rate_type ENUM('monthly','daily') DEFAULT 'daily',
  fine_rate_type ENUM('monthly','daily') DEFAULT 'daily',
  overtime_enabled TINYINT(4) DEFAULT 1,
  fine_enabled TINYINT(4) DEFAULT 1,
  allowed_break_minutes INT(11) DEFAULT 30,
  break_excess_penalty_type ENUM('fixed','percentage') DEFAULT 'fixed',
  break_excess_penalty_value DECIMAL(10,2) DEFAULT 0.00,
  travel_allowance_type ENUM('fixed','percentage') DEFAULT 'fixed',
  travel_allowance_value DECIMAL(10,2) DEFAULT 0.00,
  other_deduction_type ENUM('fixed','percentage') DEFAULT 'percentage',
  other_deduction_value DECIMAL(10,2) DEFAULT 0.00,
  create_by VARCHAR(50) NOT NULL,
  modify_by VARCHAR(50) NOT NULL,
  create_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modify_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted ENUM('0','1') DEFAULT '0',
  deleted_by VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_staff_salaries_salary_id (salary_id),
  KEY idx_staff_salaries_map (map_id),
  KEY idx_staff_salaries_user_branch (username, branch_id),
  KEY idx_staff_salaries_effective (username, branch_id, effective_from),
  KEY idx_staff_salaries_active (username, branch_id, is_active),
  KEY idx_staff_salaries_type (salary_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO staff_salaries (
  salary_id,
  map_id,
  username,
  branch_id,
  salary_type,
  amount,
  monthly_working_hours,
  effective_from,
  effective_to,
  is_active,
  working_hours_start,
  working_hours_end,
  expected_hours,
  grace_period_minutes,
  overtime_rate_type,
  fine_rate_type,
  overtime_enabled,
  fine_enabled,
  allowed_break_minutes,
  break_excess_penalty_type,
  break_excess_penalty_value,
  travel_allowance_type,
  travel_allowance_value,
  other_deduction_type,
  other_deduction_value,
  create_by,
  modify_by,
  create_date,
  modify_date,
  is_deleted,
  deleted_by
)
SELECT
  a.salary_id,
  a.map_id,
  a.username,
  a.branch_id,
  COALESCE(s.salary_type, 'fixed'),
  COALESCE(s.amount, 0),
  s.monthly_working_hours,
  a.effective_from,
  a.effective_to,
  a.is_active,
  a.working_hours_start,
  a.working_hours_end,
  a.expected_hours,
  a.grace_period_minutes,
  a.overtime_rate_type,
  a.fine_rate_type,
  a.overtime_enabled,
  a.fine_enabled,
  a.allowed_break_minutes,
  a.break_excess_penalty_type,
  a.break_excess_penalty_value,
  a.travel_allowance_type,
  a.travel_allowance_value,
  a.other_deduction_type,
  a.other_deduction_value,
  a.create_by,
  a.modify_by,
  a.create_date,
  a.modify_date,
  a.is_deleted,
  a.deleted_by
FROM staff_salary_assignments a
LEFT JOIN salaries s ON s.salary_id = a.salary_id
WHERE NOT EXISTS (
  SELECT 1 FROM staff_salaries ss WHERE ss.salary_id = a.salary_id
);

DROP TABLE IF EXISTS staff_salary_assignments;
DROP TABLE IF EXISTS salaries;
