CREATE TABLE IF NOT EXISTS `in_app_voice_calls` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `call_id` CHAR(36) NOT NULL,
  `branch_id` VARCHAR(50) NOT NULL,
  `caller_username` VARCHAR(50) NOT NULL,
  `client_username` VARCHAR(50) NOT NULL,
  `caller_name` VARCHAR(150) NOT NULL,
  `client_name` VARCHAR(150) NOT NULL,
  `provider_room` VARCHAR(80) NOT NULL,
  `status` ENUM('ringing', 'accepted', 'rejected', 'cancelled', 'missed', 'ended', 'failed') NOT NULL DEFAULT 'ringing',
  `idempotency_key` VARCHAR(100) NULL,
  `expires_at` DATETIME NOT NULL,
  `accepted_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  `end_reason` VARCHAR(40) NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_in_app_voice_call_id` (`call_id`),
  UNIQUE KEY `uk_in_app_voice_room` (`provider_room`),
  UNIQUE KEY `uk_in_app_voice_idempotency` (`caller_username`, `idempotency_key`),
  KEY `idx_in_app_voice_client_active` (`client_username`, `status`, `expires_at`),
  KEY `idx_in_app_voice_caller_active` (`caller_username`, `status`, `create_date`),
  KEY `idx_in_app_voice_branch_history` (`branch_id`, `create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
