export const TEMPLATELIST = [
    {
        name: "payment reminder",
        description: "Payment reminder template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{email}}", label: "Client email" },
            { key: "{{firm_name}}", label: "Firm name" },
            { key: "{{amount}}", label: "Due amount" },
            { key: "{{due_date}}", label: "Payment due date" },
            { key: "{{balance}}", label: "Outstanding balance" },
        ],
    },
    {
        name: "payment receive",
        description: "Payment receive template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{email}}", label: "Client email" },
            { key: "{{received_amount}}", label: "Received amount" },
            { key: "{{received_by}}", label: "Received by" },
            { key: "{{transaction_date}}", label: "Transaction date" },
            { key: "{{invoice_no}}", label: "Invoice number" },
            { key: "{{opening_balance}}", label: "Opening balance" },
            { key: "{{closing_balance}}", label: "Closing balance" },
        ],
    },
    {
        name: "payment",
        description: "Payment template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{email}}", label: "Client email" },
            { key: "{{firm_name}}", label: "Firm name" },
            { key: "{{amount}}", label: "Payment amount" },
            { key: "{{invoice_no}}", label: "Invoice number" },
        ],
    },
    {
        name: "birthday wish",
        description: "Birthday wish template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{firm_name}}", label: "Firm name" },
        ],
    },
    {
        name: "task create",
        description: "Task create template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{email}}", label: "Client email" },
            { key: "{{firm_name}}", label: "Firm name" },
            { key: "{{service_name}}", label: "Service name" },
            { key: "{{due_date}}", label: "Task due date" },
            { key: "{{created_by}}", label: "Created by user's name" },
            { key: "{{created_date}}", label: "Created date" },
            { key: "{{fees}}", label: "Task fees" },
            { key: "{{payment_link}}", label: "Payment link" },
            { key: "{{balance}}", label: "Current Balance" },
        ],
    },
    {
        name: "task complete",
        description: "Task complete template",
        available_variables: [
            { key: "{{name}}", label: "Client name" },
            { key: "{{mobile}}", label: "Client mobile number" },
            { key: "{{email}}", label: "Client email" },
            { key: "{{firm_name}}", label: "Firm name" },
            { key: "{{service_name}}", label: "Service name" },
            { key: "{{due_date}}", label: "Task due date" },
            { key: "{{completed_by}}", label: "Completed by user's name" },
            { key: "{{fees}}", label: "Task fees" },
            { key: "{{payment_link}}", label: "Payment link" },
            { key: "{{balance}}", label: "Current Balance" },
        ],
    },
];